version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    ports:
    - "5442:5432"
    volumes:
    - "${PWD}/pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
    driver: local
